### ISSUE TITLE
Unable to generate fake for stackEchange.Redis

### ISSUE THREAD

**Issue by AbhishekAdusumilli** [StackExchange/StackExchange.Redis#1348]
Hi ,
I am trying implement unit test cases .So i want to generate fake for stackEchange.Redis. But it is not generting

**Comment by mgravell** [comment]
And what tool are you using to generate that? Code?

**Comment by AbhishekAdusumilli** [comment]
Visual studio

**Comment by mgravell** [comment]
can you be more specific? what ***exactly*** are you doing? if you wanted me to see the same thing that you're seeing, so that I can try to fix it: what would I do? If I try to wildly guess, it is likely that I'm not testing the same scenario.

**Comment by AbhishekAdusumilli** [comment]
Hi mgravell,

Please find the details.

I have test Project in that i have reference to stackexchange.Redis with version 1.x .For that dll i am able to generate fakes by rightclick on the dll and clicking on "Add Fake Assembly". But when i upgrade dll to 2.x.I am unable to generate fake for this assembly.

It is failing with the below errors 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "msshrtmi", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

3>xxx\RedisCacheProvider.Tests\f.cs(11813,100): error CS0306: The type 'Span<T>' may not be used as a type argument [xxx\RedisCacheProvider.Tests\obj\Debug\Fakes\ser\f.csproj]
3>xxx\RedisCacheProvider.Tests\f.cs(11661,146): error CS0306: The type 'Span<T>' may not be used as a type argument [xxx\RedisCacheProvider.Tests\obj\Debug\Fakes\ser\f.csproj]
3>xxx\RedisCacheProvider.Tests\f.cs(14783,126): error CS0306: The type 'ReadOnlySpan<byte>' may not be used as a type argument [xxx\RedisCacheProvider.Tests\obj\Debug\Fakes\ser\f.csproj]
3>xxx\RedisCacheProvider.Tests\f.cs(14795,135): error CS0306: The type 'ReadOnlySpan<byte>' may not be used as a type argument [xxx\RedisCacheProvider.Tests\obj\Debug\Fakes\ser\f.csproj]
3>xxx\RedisCacheProvider.Tests\f.cs(14807,133): error CS0306: The type 'ReadOnlySpan<byte>' may not be used as a type argument [xxx\RedisCacheProvider.Tests\obj\Debug\Fakes\ser\f.csproj]
3>xxx\RedisCacheProvider.Tests\f.cs(10867,123): error CS0306: The type 'ReadOnlySpan<byte>' may not be used as a type argument [xxx\RedisCacheProvider.Tests\obj\Debug\Fakes\ser\f.csproj]
3>xxx\RedisCacheProvider.Tests\f.cs(10879,129): error CS0306: The type 'ReadOnlySpan<byte>' may not be used as a type argument [xxx\RedisCacheProvider.Tests\obj\Debug\Fakes\ser\f.csproj]
<img width="236" alt="Sample" src="https://user-images.githubusercontent.com/17424454/74519616-10fefd80-4f3c-11ea-8f88-713f1ed34117.PNG">

**Comment by mgravell** [comment]
k; this sounds like a problem that isn't going to be solvable by us; it anything, it sounds like a glitch in the VS "fakes" functionality. I'm not even going to test it myself, as *right now* I only have "Professional" installed, and I believe this requires "Enterprise" (I *have* an "Enterprise" licence - I'm just ... mostly not using it).

My advice here would be: try another mocking framework. Now, if there are APIs that are genuinely not readily mockable by *normal mocking tools*, then I'm more than happy to consider API changes to help with that - the pending pre-release build has a number of tweaks for that reason (but: from what I can see, those changes have nothing to do with the errors you've shown).

**Comment by NickCraver** [comment]
Answered above - closing this out for inactivity

**Comment by Nini2503** [comment]
Hello @AbhishekAdusumilli  did it solve your problem, we are facing same issue with cosmos client fakes
